// Angular React Vue - Academind/vue/vue-framework-intro/src/components/User.vue
<template>
  <div id="user">
    <h3>The user</h3>
    <p>My username is {{username}}</p>
    <app-info />
  </div>
</template>
<script>
import Info from "./Info";
export default {
  data() {
    return {
      username: "Lukas"
    };
  },
  components: {
    "app-info": Info
  }
};
</script>

<style>
</style>

// Angular React Vue - Academind/angular/angular-framwork-intro/src/app/user/user.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-user',
  templateUrl: './user.component.html',
  styleUrls: ['./user.component.css'],
})
export class UserComponent {
  username: String = 'Lukas';
}

<h1>Username</h1>
<p>My username is {{ username }}</p>
<app-info></app-info>
